### ISSUE TITLE
async inside useEffect

### ISSUE THREAD

**Issue by ShahriarKh** [PaulBratslavsky/plugin-dev-101-strapi-v4-complete#2]
Inside `HomePage/index.js`, the correct way to use async function inside `useEffect` is something like:
```jsx
useEffect(() => {
  const fetchData = async () => {
    if (!isLoading) setIsLoading(true);
    const todo = await todoRequests.getAllTodos();
    setTodoData(todo);
    setIsLoading(false);
  };

  fetchData();
}, []);
```
Otherwise, the app will throw errors in newer versions of react.

**Comment by PaulBratslavsky** [comment]
@ShahriarKh thank you for the feedback.  Yes, I was surpriced that react did not throw the errror.  This issue has been resolved.  You can see the PR  https://github.com/PaulBratslavsky/plugin-dev-101-strapi-v4-complete/pull/3

Thank you.
